In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r'../data/raw/Mall_Customers.csv')

In [3]:
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [ ]:
num_features = df[['Age', 'Annual Income (k$)', 'Spending Score (1-100)']].values
cat_features = df[['Gender']].values

In [9]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
num_scaled = scaler.fit_transform(num_features)
num_scaled[:5]

array([[-1.42456879, -1.73899919, -0.43480148],
       [-1.28103541, -1.73899919,  1.19570407],
       [-1.3528021 , -1.70082976, -1.71591298],
       [-1.13750203, -1.70082976,  1.04041783],
       [-0.56336851, -1.66266033, -0.39597992]])

In [10]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder()
cat_encoded = encoder.fit_transform(cat_features).toarray()
cat_encoded[:5]

array([[0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [12]:
X = np.concatenate([num_scaled, cat_encoded], axis=1)
print("Final shape:", X.shape)
X[:5]

Final shape: (200, 5)

array([[-1.42456879, -1.73899919, -0.43480148,  0.        ,  1.        ],
       [-1.28103541, -1.73899919,  1.19570407,  0.        ,  1.        ],
       [-1.3528021 , -1.70082976, -1.71591298,  1.        ,  0.        ],
       [-1.13750203, -1.70082976,  1.04041783,  1.        ,  0.        ],
       [-0.56336851, -1.66266033, -0.39597992,  1.        ,  0.        ]])

In [23]:
from sklearn.decomposition import PCA
pca = PCA(n_components=0.95, random_state=45)
X_pca = pca.fit_transform(X)
print("PCA shape:", X_pca.shape)
X_pca[:5]

PCA shape: (200, 4)

array([[-0.57572361, -1.68487363, -1.31521   , -0.98475001],
       [-1.62359494, -1.72648138, -0.06014863, -1.04960078],
       [ 0.27961435, -1.72531425, -2.18257447,  0.48572422],
       [-1.51106396, -1.79620462, -0.08024178,  0.37456363],
       [-0.09546842, -1.7073466 , -0.69068401,  0.47395416]])

In [24]:
X_pca_df = pd.DataFrame(X_pca, columns=[f'PC{i+1}' for i in range(X_pca.shape[1])])
X_pca_df.head()

        PC1       PC2       PC3       PC4
0 -0.575724 -1.684874 -1.315210 -0.984750
1 -1.623595 -1.726481 -0.060149 -1.049601
2  0.279614 -1.725314 -2.182574  0.485724
3 -1.511064 -1.796205 -0.080242  0.374564
4 -0.095468 -1.707347 -0.690684  0.473954

In [22]:
X_pca_df.to_csv(r'../data/processed/mall_customers_pca.csv', index=False)